services:
  app:
    image: ghcr.io/makoncline/daylilycatalog:${IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./next-cache:/app/.next/cache
    networks:
      - edge

networks:
  edge:
    external: true
