const SECOND = 1;
const MINUTE = 60 * SECOND;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;
const WEEK = 7 * DAY;

const SECOND_IN_MS = 1000;

export const CACHE_CONFIG = {
  DURATIONS: {
    SECOND,
    MINUTE,
    HOUR,
    DAY,
    WEEK,
  },
  PUBLIC: {
    CULTIVAR_PAGE_REVALIDATE_SECONDS: HOUR,
    STATIC_REVALIDATE_SECONDS: 30 * MINUTE,
    PROFILE_REVALIDATE_SECONDS: 15 * MINUTE,
    SITEMAP_REVALIDATE_SECONDS: DAY,
    SEARCH: {
      CLIENT_STALE_TIME_MS: DAY * SECOND_IN_MS,
      CLIENT_GC_TIME_MS: DAY * SECOND_IN_MS * 2,
      CLIENT_REFETCH_ON_MOUNT: true as const,
      CLIENT_REFETCH_ON_WINDOW_FOCUS: false,
      CLIENT_REFETCH_ON_RECONNECT: false,
    },
    CLIENT_QUERY: {
      STALE_TIME_MS: DAY * SECOND_IN_MS,
      GC_TIME_MS: DAY * SECOND_IN_MS * 2,
      REFETCH_ON_MOUNT: true as const,
      REFETCH_ON_WINDOW_FOCUS: false,
      REFETCH_ON_RECONNECT: false,
    },
  },
} as const;
