export const CATALOG_IMPORT_PREVIEW_ROW_COUNT = 10;
export const CATALOG_IMPORT_PUBLIC_SAMPLE_ROW_LIMIT = 20;
export const CATALOG_IMPORT_PUBLIC_MATCH_BATCH_SIZE = 50;
export const CATALOG_IMPORT_PRO_MATCH_BATCH_SIZE = 250;
export const CATALOG_IMPORT_DRAFT_STORAGE_KEY = "catalog-importer-draft:v1";
export const CATALOG_IMPORT_DRAFT_MAX_LENGTH = 4_000_000;
