import { notFound } from "next/navigation";
import { isHermeticMode, isRealisticDataMode } from "@/lib/hermetic/runtime.js";
import { db } from "@/server/db";

export const dynamic = "force-dynamic";

interface EmailEvent {
  audience: string;
  body: string;
  subject: string;
  to: string;
  type: "email";
}

function parseEmailEvent(value: string): EmailEvent | null {
  try {
    const event = JSON.parse(value) as Partial<EmailEvent>;
    return event.type === "email" &&
      typeof event.audience === "string" &&
      typeof event.body === "string" &&
      typeof event.subject === "string" &&
      typeof event.to === "string"
      ? (event as EmailEvent)
      : null;
  } catch {
    return null;
  }
}

export default async function LocalEmailPage() {
  if (!isHermeticMode() && !isRealisticDataMode()) notFound();

  const rows = await db.keyValue.findMany({
    where: { key: { startsWith: "hermetic:event:email:" } },
    orderBy: { createdAt: "desc" },
  });
  const messages = rows.flatMap((row) => {
    const event = parseEmailEvent(row.value);
    return event ? [{ ...event, id: row.key }] : [];
  });

  return (
    <main className="mx-auto min-h-svh max-w-4xl space-y-6 px-6 py-12">
      <div>
        <p className="text-primary text-sm font-medium">Local integration</p>
        <h1 className="text-3xl font-semibold">Email inbox</h1>
        <p className="text-muted-foreground mt-2 text-sm">
          Messages generated by the real application are captured here instead
          of being delivered through SES.
        </p>
      </div>

      {messages.length === 0 ? (
        <p className="rounded-lg border p-6">No messages have been sent.</p>
      ) : (
        <div className="space-y-6">
          {messages.map((message) => (
            <article className="rounded-lg border p-6" key={message.id}>
              <dl className="mb-5 grid gap-2 text-sm sm:grid-cols-[5rem_1fr]">
                <dt className="text-muted-foreground">To</dt>
                <dd>{message.to}</dd>
                <dt className="text-muted-foreground">Audience</dt>
                <dd>{message.audience}</dd>
                <dt className="text-muted-foreground">Subject</dt>
                <dd className="font-medium">{message.subject}</dd>
              </dl>
              <pre className="bg-muted overflow-x-auto rounded-md p-4 font-sans text-sm whitespace-pre-wrap">
                {message.body}
              </pre>
            </article>
          ))}
        </div>
      )}
    </main>
  );
}
