const ONE_HOUR_SECONDS = 60 * 60;
const ONE_DAY_SECONDS = 24 * ONE_HOUR_SECONDS;

export const PUBLIC_CACHE_CONFIG = {
  REVALIDATE_SECONDS: {
    PAGE: {
      HOME: ONE_DAY_SECONDS,
      CATALOGS: ONE_DAY_SECONDS,
      PROFILE: ONE_DAY_SECONDS,
      CULTIVAR: ONE_DAY_SECONDS,
    },
    DATA: {
      PUBLIC_ROUTER_LISTINGS: ONE_DAY_SECONDS,
      HOME_METADATA: ONE_DAY_SECONDS,
      HOME_JSON_LD: ONE_DAY_SECONDS,
      CATALOGS_METADATA: ONE_DAY_SECONDS,
      PROFILE_METADATA: ONE_DAY_SECONDS,
      PROFILE_JSON_LD: ONE_DAY_SECONDS,
      LISTING_METADATA: ONE_DAY_SECONDS,
      LISTING_JSON_LD: ONE_DAY_SECONDS,
    },
  },
  DYNAMIC_PARAMS: {
    PROFILE_PAGE: true,
    CULTIVAR_PAGE: true,
  },
} as const;
