"use client";

// eslint-disable react/no-danger -- QR SVG markup is generated by the tag model.
import * as React from "react";
import { TriangleAlert } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { cn } from "@/lib/utils";
import {
  QR_SIZE_INCHES,
  TAG_SPACER_HEIGHT_INCHES,
  buildQrCodeSvgMarkup,
  getTagPreviewWarnings,
  resolveCellFontSizePx,
} from "./tag-designer-model";
import type { TagPreviewData } from "./tag-designer-model";

function QrCodeSvg({
  qrCodeUrl,
  className,
  style,
}: {
  qrCodeUrl: string;
  className?: string;
  style?: React.CSSProperties;
}) {
  const qrSvgMarkup = React.useMemo(
    () => buildQrCodeSvgMarkup(qrCodeUrl),
    [qrCodeUrl],
  );

  return (
    <div
      aria-hidden="true"
      className={className}
      style={style}
      dangerouslySetInnerHTML={{ __html: qrSvgMarkup }}
    />
  );
}

export function TagPreviewCard({
  tag,
  widthInches,
  heightInches,
  className,
}: {
  tag: TagPreviewData;
  widthInches: number;
  heightInches: number;
  className?: string;
}) {
  return (
    <article
      className={cn(
        "grid shrink-0 items-center gap-2 overflow-hidden border border-dashed bg-white p-2 text-black",
        tag.qrCodeUrl ? "grid-cols-[minmax(0,1fr)_auto]" : "grid-cols-1",
        className,
      )}
      style={{
        width: `${widthInches}in`,
        height: `${heightInches}in`,
      }}
    >
      <div className="min-w-0">
        {tag.rows.map((row) => (
          <React.Fragment key={row.id}>
            {row.isSpacer ? (
              <div
                aria-hidden="true"
                style={{ height: `${TAG_SPACER_HEIGHT_INCHES}in` }}
              />
            ) : (
              <div className="flex min-w-0 items-baseline justify-between gap-x-2">
                {row.cells.map((cell) => (
                  <p
                    key={cell.id}
                    className={cn(
                      "min-w-0 overflow-hidden leading-tight whitespace-nowrap",
                      row.cells.length === 1 && "w-full",
                      cell.bold && "font-semibold",
                      cell.italic && "italic",
                      cell.underline && "underline",
                      cell.textAlign === "center" && "text-center",
                      cell.textAlign === "right" && "text-right",
                      cell.textAlign === "left" && "text-left",
                    )}
                    style={{
                      flex: `${cell.width} 1 0`,
                      fontSize: `${resolveCellFontSizePx(
                        cell,
                        row,
                        widthInches,
                        Boolean(tag.qrCodeUrl),
                        heightInches,
                        tag.rows,
                      )}px`,
                    }}
                  >
                    {cell.text}
                  </p>
                ))}
              </div>
            )}
          </React.Fragment>
        ))}
      </div>

      {tag.qrCodeUrl ? (
        <QrCodeSvg
          qrCodeUrl={tag.qrCodeUrl}
          className="shrink-0 bg-white [&_svg]:block [&_svg]:h-full [&_svg]:w-full"
          style={{
            width: `${QR_SIZE_INCHES}in`,
            height: `${QR_SIZE_INCHES}in`,
          }}
        />
      ) : null}
    </article>
  );
}

interface TagDesignerPreviewProps {
  listingsCount: number;
  previewTags: TagPreviewData[];
  visiblePreviewTags: TagPreviewData[];
  widthInches: number;
  heightInches: number;
}

export function TagDesignerPreview({
  listingsCount,
  previewTags,
  visiblePreviewTags,
  widthInches,
  heightInches,
}: TagDesignerPreviewProps) {
  const previewWarnings = getTagPreviewWarnings({
    tags: previewTags,
    widthInches,
    heightInches,
  });

  return (
    <section
      className="flex flex-col gap-4"
      aria-labelledby="tag-preview-title"
    >
      <div className="flex items-center justify-between">
        <h3 id="tag-preview-title" className="text-sm font-medium">
          Preview
        </h3>
        <div className="flex items-center gap-2">
          {listingsCount === 0 ? (
            <p className="text-muted-foreground text-xs">
              Sample preview: select listings below
            </p>
          ) : null}
          {listingsCount > 0 &&
          previewTags.length > visiblePreviewTags.length ? (
            <p className="text-muted-foreground text-xs">
              Showing first {visiblePreviewTags.length} of {previewTags.length}{" "}
              tags
            </p>
          ) : null}
        </div>
      </div>

      {previewWarnings.length > 0 ? (
        <Alert>
          <TriangleAlert />
          <AlertTitle>Check the tag layout</AlertTitle>
          <AlertDescription>
            <ul className="list-disc pl-4">
              {previewWarnings.map((warning) => (
                <li key={warning}>{warning}</li>
              ))}
            </ul>
          </AlertDescription>
        </Alert>
      ) : null}

      {visiblePreviewTags.length > 0 ? (
        <div className="flex flex-col gap-2">
          <p className="text-muted-foreground text-xs sm:hidden">
            Swipe sideways to view full-size tags.
          </p>
          <div
            role="region"
            aria-label="Tag previews"
            tabIndex={0}
            className="flex flex-nowrap gap-3 overflow-x-auto pb-1 sm:flex-wrap"
          >
            {visiblePreviewTags.map((tag) => (
              <TagPreviewCard
                key={tag.id}
                tag={tag}
                widthInches={widthInches}
                heightInches={heightInches}
                className="border-border rounded-md"
              />
            ))}
          </div>
        </div>
      ) : (
        <p className="text-muted-foreground text-sm">
          Select listings from the table below to preview and print tags.
        </p>
      )}
    </section>
  );
}
