services:
  app:
    image: ghcr.io/makoncline/daylilycatalog:${IMAGE_TAG}
    restart: unless-stopped
    mem_limit: 1400m
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./next-cache:/app/apps/main/.next/cache
    networks:
      - edge

networks:
  edge:
    external: true
