name: Database Backup

on:
  schedule:
    # Runs at 02:00 UTC every day
    - cron: "0 2 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Turso CLI
        run: |
          curl -sSfL https://get.turso.tech/install.sh | sh -s -- -b /usr/local/bin
          turso --version

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Run backup script
        env:
          TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
          CI: true
        run: bash scripts/db-backup.sh
