name: E2E Tests (Playwright)

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Create .env.test
        run: |
          cat > .env.test << 'EOF'
          NODE_ENV=test
          LOCAL_DATABASE_URL=file:./test-results/ci-test.sqlite
          SKIP_ENV_VALIDATION=true

          # Clerk (Testing)
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_CLERK_FRONTEND_API=${{ secrets.NEXT_PUBLIC_CLERK_FRONTEND_API }}
          CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}
          EOF

      - name: Run Playwright tests
        run: npm run test

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report
            test-results
